print("done")
print(237869)
print(str(8258.998020887375))
puzzle = [['K','K','K','K','K','K','K','K','K','K','K','K'],['K','O','O','O','O','O','O','O','O','O','O','K'],['K','O','K','K','K','K','Y','Y','G','G','O','K']]
puzzle.append(['K','O','K','Y','Y','Y','Y','G','G','O','O','K'])
puzzle.append(['K','O','K','P','P','O','O','O','O','O','Q','K'])
puzzle.append(['K','K','K','R','P','O','Q','Q','Q','Q','Q','K'])
puzzle.append(['R','R','R','R','P','A','A','R','K','K','K','K'])
puzzle.append(['R','D','D','D','D','A','W','R','R','R','R','R'])
puzzle.append(['R','A','A','A','A','A','W','W','W','W','W','R'])
puzzle.append(['R','A','B','B','B','B','B','B','B','B','B','R'])
puzzle.append(['R','A','A','A','A','A','A','A','A','A','A','R'])
puzzle.append(['R','R','R','R','R','R','R','R','R','R','R','R'])
for i in range(12):
    print(puzzle[i])